wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Adipose_Tissue
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Adrenal_Gland
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Adult_Liver
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Aorta
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Brain_Germinal_Matrix
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Brain_Hippocampus_Middle
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Breast_Luminal_Epithelial_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Breast_Myoepithelial_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Esophagus
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Fetal_Intestine_Large
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Fetal_Intestine_Small
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Fetal_Muscle_Leg
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Fetal_Thymus
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Gastric
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H1_BMP4_Derived_Mesendoderm_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H1_BMP4_Derived_Trophoblast_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H1_Cell_Line
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H1_Derived_Mesenchymal_Stem_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H1_Derived_Neuronal_Progenitor_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/H9_Cell_Line
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/HUES64_Cell_Line
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/IMR90_Cell_Line
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Left_Ventricle
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Lung
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Mobilized_CD34_Primary_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Neurosphere_Cultured_Cells_Cortex_Derived
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Neurosphere_Cultured_Cells_Ganglionic_Eminence_Derived
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Ovary
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Pancreas
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Penis_Foreskin_Fibroblast_Primary_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Penis_Foreskin_Keratinocyte_Primary_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Psoas_Muscle
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Right_Atrium
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Right_Ventricle
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Sigmoid_Colon
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Small_Intestine
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Spleen
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Testis_Spermatozoa_Primary_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/Thymus
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/UCSF-4star
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/hESC_Derived_CD184+_Endoderm_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/hESC_Derived_CD56+_Ectoderm_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/hESC_Derived_CD56+_Mesoderm_Cultured_Cells
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/iPS_DF_19.11_Cell_Line
wget -r  http://www.genboree.org/EdaccData/Current-Release/experiment-sample/Bisulfite-Seq/iPS_DF_6.9_Cell_Line
